In [127]:
import pandas as pd
import numpy as np

In [128]:
from sklearn.preprocessing import OrdinalEncoder

In [129]:
df=pd.read_csv('Employee_Attrition_Dataset_train.csv')

In [130]:
df.head()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

In [131]:
df.shape

(59598, 24)

In [132]:
df.columns

Index(['Employee ID', 'Age', 'Gender', 'Years at Company', 'Job Role',
       'Monthly Income', 'Work-Life Balance', 'Job Satisfaction',
       'Performance Rating', 'Number of Promotions', 'Overtime',
       'Distance from Home', 'Education Level', 'Marital Status',
       'Number of Dependents', 'Job Level', 'Company Size', 'Company Tenure',
       'Remote Work', 'Leadership Opportunities', 'Innovation Opportunities',
       'Company Reputation', 'Employee Recognition', 'Attrition'],
      dtype='object')

In [133]:
df = df[['Employee ID', 'Gender', 'Job Satisfaction', 'Marital Status',
         'Education Level', 'Job Level', 'Company Size',
         'Remote Work', 'Company Reputation', 'Employee Recognition']]

In [134]:
df.head()

,Employee ID,Gender,Job Satisfaction,Marital Status,Education Level,Job Level,Company Size,Remote Work,Company Reputation,Employee Recognition
0,8410,Male,Medium,Married,Associate Degree,Mid,Medium,No,Excellent,Medium
1,64756,Female,High,Divorced,Master’s Degree,Mid,Medium,No,Fair,Low
2,30257,Female,High,Married,Bachelor’s Degree,Mid,Medium,No,Poor,Low
3,65791,Female,High,Single,High School,Mid,Small,Yes,Good,Medium
4,65026,Male,Very High,Divorced,High School,Senior,Medium,No,Fair,Medium

In [135]:
df['Job Satisfaction'].unique()

array(['Medium', 'High', 'Very High', 'Low'], dtype=object)

In [136]:
df['Job Level'].unique()

array(['Mid', 'Senior', 'Entry'], dtype=object)

In [137]:
df['Company Size'].unique()

array(['Medium', 'Small', 'Large'], dtype=object)

In [138]:
df['Company Reputation'].unique()

array(['Excellent', 'Fair', 'Poor', 'Good'], dtype=object)

In [139]:
df['Employee Recognition'].unique()

array(['Medium', 'Low', 'High', 'Very High'], dtype=object)

In [140]:
df['Education Level'].unique()

array(['Associate Degree', 'Master’s Degree', 'Bachelor’s Degree',
       'High School', 'PhD'], dtype=object)

In [141]:
ordinal_cols= ['Job Satisfaction','Job Level', 'Company Size', 'Company Reputation', 'Employee Recognition', 'Education Level']

In [142]:
oe = OrdinalEncoder(categories=[[ 'Low','Medium', 'High', 'Very High'],
                                ['Entry','Mid', 'Senior'],
                                ['Small','Medium', 'Large'],
                                ['Poor','Fair','Good', 'Excellent'],
                                ['Low','Medium', 'High', 'Very High'],
                                ['High School', 'Associate Degree','Bachelor’s Degree', 'Master’s Degree', 'PhD']])

In [143]:
df[ordinal_cols] = oe.fit_transform(df[ordinal_cols])
df.head()

,Employee ID,Gender,Job Satisfaction,Marital Status,Education Level,Job Level,Company Size,Remote Work,Company Reputation,Employee Recognition
0,8410,Male,1.0,Married,1.0,1.0,1.0,No,3.0,1.0
1,64756,Female,2.0,Divorced,3.0,1.0,1.0,No,1.0,0.0
2,30257,Female,2.0,Married,2.0,1.0,1.0,No,0.0,0.0
3,65791,Female,2.0,Single,0.0,1.0,0.0,Yes,2.0,1.0
4,65026,Male,3.0,Divorced,0.0,2.0,1.0,No,1.0,1.0

In [144]:
oe.categories_

[array(['Low', 'Medium', 'High', 'Very High'], dtype=object),
 array(['Entry', 'Mid', 'Senior'], dtype=object),
 array(['Small', 'Medium', 'Large'], dtype=object),
 array(['Poor', 'Fair', 'Good', 'Excellent'], dtype=object),
 array(['Low', 'Medium', 'High', 'Very High'], dtype=object),
 array(['High School', 'Associate Degree', 'Bachelor’s Degree',
        'Master’s Degree', 'PhD'], dtype=object)]

In [145]:
df.head()

,Employee ID,Gender,Job Satisfaction,Marital Status,Education Level,Job Level,Company Size,Remote Work,Company Reputation,Employee Recognition
0,8410,Male,1.0,Married,1.0,1.0,1.0,No,3.0,1.0
1,64756,Female,2.0,Divorced,3.0,1.0,1.0,No,1.0,0.0
2,30257,Female,2.0,Married,2.0,1.0,1.0,No,0.0,0.0
3,65791,Female,2.0,Single,0.0,1.0,0.0,Yes,2.0,1.0
4,65026,Male,3.0,Divorced,0.0,2.0,1.0,No,1.0,1.0

In [146]:
# Label Encoding

In [147]:
from sklearn.preprocessing import LabelEncoder

In [148]:
le = LabelEncoder()

In [149]:
df['Gender_Encode']=le.fit_transform(df['Gender'])
df['Marital Status Encode']= le.fit_transform(df['Marital Status'])

In [150]:
df.head()

,Employee ID,Gender,Job Satisfaction,Marital Status,Education Level,Job Level,Company Size,Remote Work,Company Reputation,Employee Recognition,Gender_Encode,Marital Status Encode
0,8410,Male,1.0,Married,1.0,1.0,1.0,No,3.0,1.0,1,1
1,64756,Female,2.0,Divorced,3.0,1.0,1.0,No,1.0,0.0,0,0
2,30257,Female,2.0,Married,2.0,1.0,1.0,No,0.0,0.0,0,1
3,65791,Female,2.0,Single,0.0,1.0,0.0,Yes,2.0,1.0,0,2
4,65026,Male,3.0,Divorced,0.0,2.0,1.0,No,1.0,1.0,1,0